
// DO NOT EDIT THIS BLOCK BELOW=== Parameters starts ===
// PLEASE DO NOT EDIT THIS FILE

import com.cloudbees.flowpdf.StepParameters

class ApplyConfigurationParameters {
    /**
    * Label: File Path, type: entry
    */
    String configurationPath
    /**
    * Label: YAML, type: textarea
    */
    String configurationYaml

    static ApplyConfigurationParameters initParameters(StepParameters sp) {
        ApplyConfigurationParameters parameters = new ApplyConfigurationParameters()

        def configurationPath = sp.getParameter('configurationPath').value
        parameters.configurationPath = configurationPath
        def configurationYaml = sp.getParameter('configurationYaml').value
        parameters.configurationYaml = configurationYaml

        return parameters
    }
}
// DO NOT EDIT THIS BLOCK ABOVE ^^^=== Parameters ends, checksum: ffd99a4a33733a20d3e85079a5af0366 ===
