
// DO NOT EDIT THIS BLOCK === Parameters starts ===
// PLEASE DO NOT EDIT THIS FILE

import com.cloudbees.flowpdf.StepParameters

class CreateMasterConfigurationParameters {
    /**
    * Label: Master Name, type: entry
    */
    String masterName
    /**
    * Label: Result Property, type: entry
    */
    String resultProperty

    static CreateMasterConfigurationParameters initParameters(StepParameters sp) {
        CreateMasterConfigurationParameters parameters = new CreateMasterConfigurationParameters()

        def masterName = sp.getRequiredParameter('masterName').value
        parameters.masterName = masterName
        def resultProperty = sp.getRequiredParameter('resultProperty').value
        parameters.resultProperty = resultProperty

        return parameters
    }
}
// DO NOT EDIT THIS BLOCK === Parameters ends, checksum: bc2dd869945507ef2d12568779a3e14b ===
