
// DO NOT EDIT THIS BLOCK BELOW=== Parameters starts ===
// PLEASE DO NOT EDIT THIS FILE

import com.cloudbees.flowpdf.StepParameters

class ExportJobToXMLParameters {
    /**
    * Label: Job Name, type: entry
    */
    String jenkinsJobName
    /**
    * Label: Result filepath, type: entry
    */
    String filePath
    /**
    * Label: saveToProperty, type: entry
    */
    String resultProperty

    static ExportJobToXMLParameters initParameters(StepParameters sp) {
        ExportJobToXMLParameters parameters = new ExportJobToXMLParameters()

        def jenkinsJobName = sp.getRequiredParameter('jenkinsJobName').value
        parameters.jenkinsJobName = jenkinsJobName
        def filePath = sp.getRequiredParameter('filePath').value
        parameters.filePath = filePath
        def resultProperty = sp.getParameter('resultProperty').value
        parameters.resultProperty = resultProperty

        return parameters
    }
}
// DO NOT EDIT THIS BLOCK ABOVE ^^^=== Parameters ends, checksum: 3711bd9728a5c02b4ffe7175a55ee8c9 ===
