
// DO NOT EDIT THIS BLOCK BELOW=== Parameters starts ===
// PLEASE DO NOT EDIT THIS FILE

import com.cloudbees.flowpdf.StepParameters

class InstallPluginParameters {
    /**
    * Label: Plugin File Path, type: entry
    */
    String pluginPath

    static InstallPluginParameters initParameters(StepParameters sp) {
        InstallPluginParameters parameters = new InstallPluginParameters()

        def pluginPath = sp.getRequiredParameter('pluginPath').value
        parameters.pluginPath = pluginPath

        return parameters
    }
}
// DO NOT EDIT THIS BLOCK ABOVE ^^^=== Parameters ends, checksum: 074959c3d7053f75902133836f7347a9 ===
