
// DO NOT EDIT THIS BLOCK === Parameters starts ===
// PLEASE DO NOT EDIT THIS FILE

import com.cloudbees.flowpdf.StepParameters

class RestartJenkinsParameters {
    /**
    * Label: Wait For Server?, type: checkbox
    */
    boolean waitForServer

    static RestartJenkinsParameters initParameters(StepParameters sp) {
        RestartJenkinsParameters parameters = new RestartJenkinsParameters()

        def waitForServer = sp.getParameter('waitForServer').value == "true"
        parameters.waitForServer = waitForServer

        return parameters
    }
}
// DO NOT EDIT THIS BLOCK === Parameters ends, checksum: 1cd8bc433ac26cfc3f9bef4254f67eae ===
