
// DO NOT EDIT THIS BLOCK === Parameters starts ===
// PLEASE DO NOT EDIT THIS FILE

import com.cloudbees.flowpdf.StepParameters

class WaitForServerParameters {
    /**
    * Label: Timeout, type: entry
    */
    String waitTimeout

    static WaitForServerParameters initParameters(StepParameters sp) {
        WaitForServerParameters parameters = new WaitForServerParameters()

        def waitTimeout = sp.getRequiredParameter('waitTimeout').value
        parameters.waitTimeout = waitTimeout

        return parameters
    }
}
// DO NOT EDIT THIS BLOCK === Parameters ends, checksum: 56755f409bc79c29f6d393487aabbe9a ===
